package com.zerozrz.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AnswerExample {
	
	private Integer startRow;
	private Integer pageSize;
	
    public Integer getStartRow() {
		return startRow;
	}

	public void setStartRow(Integer startRow) {
		this.startRow = startRow;
	}

	public Integer getPageSize() {
		return pageSize;
	}

	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table answer
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table answer
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table answer
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public AnswerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table answer
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAnswerIdIsNull() {
            addCriterion("answer_id is null");
            return (Criteria) this;
        }

        public Criteria andAnswerIdIsNotNull() {
            addCriterion("answer_id is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerIdEqualTo(Integer value) {
            addCriterion("answer_id =", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotEqualTo(Integer value) {
            addCriterion("answer_id <>", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdGreaterThan(Integer value) {
            addCriterion("answer_id >", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("answer_id >=", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdLessThan(Integer value) {
            addCriterion("answer_id <", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdLessThanOrEqualTo(Integer value) {
            addCriterion("answer_id <=", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdIn(List<Integer> values) {
            addCriterion("answer_id in", values, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotIn(List<Integer> values) {
            addCriterion("answer_id not in", values, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdBetween(Integer value1, Integer value2) {
            addCriterion("answer_id between", value1, value2, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("answer_id not between", value1, value2, "answerId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdIsNull() {
            addCriterion("survey_id is null");
            return (Criteria) this;
        }

        public Criteria andSurveyIdIsNotNull() {
            addCriterion("survey_id is not null");
            return (Criteria) this;
        }

        public Criteria andSurveyIdEqualTo(Integer value) {
            addCriterion("survey_id =", value, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdNotEqualTo(Integer value) {
            addCriterion("survey_id <>", value, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdGreaterThan(Integer value) {
            addCriterion("survey_id >", value, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("survey_id >=", value, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdLessThan(Integer value) {
            addCriterion("survey_id <", value, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdLessThanOrEqualTo(Integer value) {
            addCriterion("survey_id <=", value, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdIn(List<Integer> values) {
            addCriterion("survey_id in", values, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdNotIn(List<Integer> values) {
            addCriterion("survey_id not in", values, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdBetween(Integer value1, Integer value2) {
            addCriterion("survey_id between", value1, value2, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("survey_id not between", value1, value2, "surveyId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andAnswerStartIsNull() {
            addCriterion("answer_start is null");
            return (Criteria) this;
        }

        public Criteria andAnswerStartIsNotNull() {
            addCriterion("answer_start is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerStartEqualTo(Date value) {
            addCriterion("answer_start =", value, "answerStart");
            return (Criteria) this;
        }

        public Criteria andAnswerStartNotEqualTo(Date value) {
            addCriterion("answer_start <>", value, "answerStart");
            return (Criteria) this;
        }

        public Criteria andAnswerStartGreaterThan(Date value) {
            addCriterion("answer_start >", value, "answerStart");
            return (Criteria) this;
        }

        public Criteria andAnswerStartGreaterThanOrEqualTo(Date value) {
            addCriterion("answer_start >=", value, "answerStart");
            return (Criteria) this;
        }

        public Criteria andAnswerStartLessThan(Date value) {
            addCriterion("answer_start <", value, "answerStart");
            return (Criteria) this;
        }

        public Criteria andAnswerStartLessThanOrEqualTo(Date value) {
            addCriterion("answer_start <=", value, "answerStart");
            return (Criteria) this;
        }

        public Criteria andAnswerStartIn(List<Date> values) {
            addCriterion("answer_start in", values, "answerStart");
            return (Criteria) this;
        }

        public Criteria andAnswerStartNotIn(List<Date> values) {
            addCriterion("answer_start not in", values, "answerStart");
            return (Criteria) this;
        }

        public Criteria andAnswerStartBetween(Date value1, Date value2) {
            addCriterion("answer_start between", value1, value2, "answerStart");
            return (Criteria) this;
        }

        public Criteria andAnswerStartNotBetween(Date value1, Date value2) {
            addCriterion("answer_start not between", value1, value2, "answerStart");
            return (Criteria) this;
        }

        public Criteria andAnswerEndIsNull() {
            addCriterion("answer_end is null");
            return (Criteria) this;
        }

        public Criteria andAnswerEndIsNotNull() {
            addCriterion("answer_end is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerEndEqualTo(Date value) {
            addCriterion("answer_end =", value, "answerEnd");
            return (Criteria) this;
        }

        public Criteria andAnswerEndNotEqualTo(Date value) {
            addCriterion("answer_end <>", value, "answerEnd");
            return (Criteria) this;
        }

        public Criteria andAnswerEndGreaterThan(Date value) {
            addCriterion("answer_end >", value, "answerEnd");
            return (Criteria) this;
        }

        public Criteria andAnswerEndGreaterThanOrEqualTo(Date value) {
            addCriterion("answer_end >=", value, "answerEnd");
            return (Criteria) this;
        }

        public Criteria andAnswerEndLessThan(Date value) {
            addCriterion("answer_end <", value, "answerEnd");
            return (Criteria) this;
        }

        public Criteria andAnswerEndLessThanOrEqualTo(Date value) {
            addCriterion("answer_end <=", value, "answerEnd");
            return (Criteria) this;
        }

        public Criteria andAnswerEndIn(List<Date> values) {
            addCriterion("answer_end in", values, "answerEnd");
            return (Criteria) this;
        }

        public Criteria andAnswerEndNotIn(List<Date> values) {
            addCriterion("answer_end not in", values, "answerEnd");
            return (Criteria) this;
        }

        public Criteria andAnswerEndBetween(Date value1, Date value2) {
            addCriterion("answer_end between", value1, value2, "answerEnd");
            return (Criteria) this;
        }

        public Criteria andAnswerEndNotBetween(Date value1, Date value2) {
            addCriterion("answer_end not between", value1, value2, "answerEnd");
            return (Criteria) this;
        }

        public Criteria andAnswerUsedtimeIsNull() {
            addCriterion("answer_usedTime is null");
            return (Criteria) this;
        }

        public Criteria andAnswerUsedtimeIsNotNull() {
            addCriterion("answer_usedTime is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerUsedtimeEqualTo(Date value) {
            addCriterion("answer_usedTime =", value, "answerUsedtime");
            return (Criteria) this;
        }

        public Criteria andAnswerUsedtimeNotEqualTo(Date value) {
            addCriterion("answer_usedTime <>", value, "answerUsedtime");
            return (Criteria) this;
        }

        public Criteria andAnswerUsedtimeGreaterThan(Date value) {
            addCriterion("answer_usedTime >", value, "answerUsedtime");
            return (Criteria) this;
        }

        public Criteria andAnswerUsedtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("answer_usedTime >=", value, "answerUsedtime");
            return (Criteria) this;
        }

        public Criteria andAnswerUsedtimeLessThan(Date value) {
            addCriterion("answer_usedTime <", value, "answerUsedtime");
            return (Criteria) this;
        }

        public Criteria andAnswerUsedtimeLessThanOrEqualTo(Date value) {
            addCriterion("answer_usedTime <=", value, "answerUsedtime");
            return (Criteria) this;
        }

        public Criteria andAnswerUsedtimeIn(List<Date> values) {
            addCriterion("answer_usedTime in", values, "answerUsedtime");
            return (Criteria) this;
        }

        public Criteria andAnswerUsedtimeNotIn(List<Date> values) {
            addCriterion("answer_usedTime not in", values, "answerUsedtime");
            return (Criteria) this;
        }

        public Criteria andAnswerUsedtimeBetween(Date value1, Date value2) {
            addCriterion("answer_usedTime between", value1, value2, "answerUsedtime");
            return (Criteria) this;
        }

        public Criteria andAnswerUsedtimeNotBetween(Date value1, Date value2) {
            addCriterion("answer_usedTime not between", value1, value2, "answerUsedtime");
            return (Criteria) this;
        }

        public Criteria andTestGoalIsNull() {
            addCriterion("test_goal is null");
            return (Criteria) this;
        }

        public Criteria andTestGoalIsNotNull() {
            addCriterion("test_goal is not null");
            return (Criteria) this;
        }

        public Criteria andTestGoalEqualTo(Integer value) {
            addCriterion("test_goal =", value, "testGoal");
            return (Criteria) this;
        }

        public Criteria andTestGoalNotEqualTo(Integer value) {
            addCriterion("test_goal <>", value, "testGoal");
            return (Criteria) this;
        }

        public Criteria andTestGoalGreaterThan(Integer value) {
            addCriterion("test_goal >", value, "testGoal");
            return (Criteria) this;
        }

        public Criteria andTestGoalGreaterThanOrEqualTo(Integer value) {
            addCriterion("test_goal >=", value, "testGoal");
            return (Criteria) this;
        }

        public Criteria andTestGoalLessThan(Integer value) {
            addCriterion("test_goal <", value, "testGoal");
            return (Criteria) this;
        }

        public Criteria andTestGoalLessThanOrEqualTo(Integer value) {
            addCriterion("test_goal <=", value, "testGoal");
            return (Criteria) this;
        }

        public Criteria andTestGoalIn(List<Integer> values) {
            addCriterion("test_goal in", values, "testGoal");
            return (Criteria) this;
        }

        public Criteria andTestGoalNotIn(List<Integer> values) {
            addCriterion("test_goal not in", values, "testGoal");
            return (Criteria) this;
        }

        public Criteria andTestGoalBetween(Integer value1, Integer value2) {
            addCriterion("test_goal between", value1, value2, "testGoal");
            return (Criteria) this;
        }

        public Criteria andTestGoalNotBetween(Integer value1, Integer value2) {
            addCriterion("test_goal not between", value1, value2, "testGoal");
            return (Criteria) this;
        }

        public Criteria andRightNumsIsNull() {
            addCriterion("right_nums is null");
            return (Criteria) this;
        }

        public Criteria andRightNumsIsNotNull() {
            addCriterion("right_nums is not null");
            return (Criteria) this;
        }

        public Criteria andRightNumsEqualTo(Integer value) {
            addCriterion("right_nums =", value, "rightNums");
            return (Criteria) this;
        }

        public Criteria andRightNumsNotEqualTo(Integer value) {
            addCriterion("right_nums <>", value, "rightNums");
            return (Criteria) this;
        }

        public Criteria andRightNumsGreaterThan(Integer value) {
            addCriterion("right_nums >", value, "rightNums");
            return (Criteria) this;
        }

        public Criteria andRightNumsGreaterThanOrEqualTo(Integer value) {
            addCriterion("right_nums >=", value, "rightNums");
            return (Criteria) this;
        }

        public Criteria andRightNumsLessThan(Integer value) {
            addCriterion("right_nums <", value, "rightNums");
            return (Criteria) this;
        }

        public Criteria andRightNumsLessThanOrEqualTo(Integer value) {
            addCriterion("right_nums <=", value, "rightNums");
            return (Criteria) this;
        }

        public Criteria andRightNumsIn(List<Integer> values) {
            addCriterion("right_nums in", values, "rightNums");
            return (Criteria) this;
        }

        public Criteria andRightNumsNotIn(List<Integer> values) {
            addCriterion("right_nums not in", values, "rightNums");
            return (Criteria) this;
        }

        public Criteria andRightNumsBetween(Integer value1, Integer value2) {
            addCriterion("right_nums between", value1, value2, "rightNums");
            return (Criteria) this;
        }

        public Criteria andRightNumsNotBetween(Integer value1, Integer value2) {
            addCriterion("right_nums not between", value1, value2, "rightNums");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table answer
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table answer
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}