package com.zerozrz.bean;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class Answer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.answer_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer answerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.survey_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer surveyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.user_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.answer_start
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8") 
    private Date answerStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.answer_end
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8") 
    private Date answerEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.answer_usedTime
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    @JsonFormat(pattern="HH:mm:ss") 
    private Date answerUsedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.test_goal
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer testGoal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.right_nums
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer rightNums;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.answer_id
     *
     * @return the value of answer.answer_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getAnswerId() {
        return answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.answer_id
     *
     * @param answerId the value for answer.answer_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setAnswerId(Integer answerId) {
        this.answerId = answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.survey_id
     *
     * @return the value of answer.survey_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getSurveyId() {
        return surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.survey_id
     *
     * @param surveyId the value for answer.survey_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setSurveyId(Integer surveyId) {
        this.surveyId = surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.user_id
     *
     * @return the value of answer.user_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.user_id
     *
     * @param userId the value for answer.user_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.answer_start
     *
     * @return the value of answer.answer_start
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Date getAnswerStart() {
        return answerStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.answer_start
     *
     * @param answerStart the value for answer.answer_start
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setAnswerStart(Date answerStart) {
        this.answerStart = answerStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.answer_end
     *
     * @return the value of answer.answer_end
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Date getAnswerEnd() {
        return answerEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.answer_end
     *
     * @param answerEnd the value for answer.answer_end
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setAnswerEnd(Date answerEnd) {
        this.answerEnd = answerEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.answer_usedTime
     *
     * @return the value of answer.answer_usedTime
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Date getAnswerUsedtime() {
        return answerUsedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.answer_usedTime
     *
     * @param answerUsedtime the value for answer.answer_usedTime
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setAnswerUsedtime(Date answerUsedtime) {
        this.answerUsedtime = answerUsedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.test_goal
     *
     * @return the value of answer.test_goal
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getTestGoal() {
        return testGoal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.test_goal
     *
     * @param testGoal the value for answer.test_goal
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setTestGoal(Integer testGoal) {
        this.testGoal = testGoal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.right_nums
     *
     * @return the value of answer.right_nums
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getRightNums() {
        return rightNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.right_nums
     *
     * @param rightNums the value for answer.right_nums
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setRightNums(Integer rightNums) {
        this.rightNums = rightNums;
    }

	@Override
	public String toString() {
		return "Answer [answerId=" + answerId + ", surveyId=" + surveyId + ", userId=" + userId + ", answerStart="
				+ answerStart + ", answerEnd=" + answerEnd + ", answerUsedtime=" + answerUsedtime + ", testGoal="
				+ testGoal + ", rightNums=" + rightNums + "]";
	}
    
    
}