package com.zerozrz.bean;

import java.util.ArrayList;
import java.util.List;

public class ReplyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public ReplyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andReplyIdIsNull() {
            addCriterion("reply_id is null");
            return (Criteria) this;
        }

        public Criteria andReplyIdIsNotNull() {
            addCriterion("reply_id is not null");
            return (Criteria) this;
        }

        public Criteria andReplyIdEqualTo(Integer value) {
            addCriterion("reply_id =", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdNotEqualTo(Integer value) {
            addCriterion("reply_id <>", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdGreaterThan(Integer value) {
            addCriterion("reply_id >", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("reply_id >=", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdLessThan(Integer value) {
            addCriterion("reply_id <", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdLessThanOrEqualTo(Integer value) {
            addCriterion("reply_id <=", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdIn(List<Integer> values) {
            addCriterion("reply_id in", values, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdNotIn(List<Integer> values) {
            addCriterion("reply_id not in", values, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdBetween(Integer value1, Integer value2) {
            addCriterion("reply_id between", value1, value2, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("reply_id not between", value1, value2, "replyId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdIsNull() {
            addCriterion("answer_id is null");
            return (Criteria) this;
        }

        public Criteria andAnswerIdIsNotNull() {
            addCriterion("answer_id is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerIdEqualTo(Integer value) {
            addCriterion("answer_id =", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotEqualTo(Integer value) {
            addCriterion("answer_id <>", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdGreaterThan(Integer value) {
            addCriterion("answer_id >", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("answer_id >=", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdLessThan(Integer value) {
            addCriterion("answer_id <", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdLessThanOrEqualTo(Integer value) {
            addCriterion("answer_id <=", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdIn(List<Integer> values) {
            addCriterion("answer_id in", values, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotIn(List<Integer> values) {
            addCriterion("answer_id not in", values, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdBetween(Integer value1, Integer value2) {
            addCriterion("answer_id between", value1, value2, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("answer_id not between", value1, value2, "answerId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIsNull() {
            addCriterion("question_id is null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIsNotNull() {
            addCriterion("question_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdEqualTo(Integer value) {
            addCriterion("question_id =", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotEqualTo(Integer value) {
            addCriterion("question_id <>", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThan(Integer value) {
            addCriterion("question_id >", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("question_id >=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThan(Integer value) {
            addCriterion("question_id <", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThanOrEqualTo(Integer value) {
            addCriterion("question_id <=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIn(List<Integer> values) {
            addCriterion("question_id in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotIn(List<Integer> values) {
            addCriterion("question_id not in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdBetween(Integer value1, Integer value2) {
            addCriterion("question_id between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("question_id not between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andReplyIdsIsNull() {
            addCriterion("reply_ids is null");
            return (Criteria) this;
        }

        public Criteria andReplyIdsIsNotNull() {
            addCriterion("reply_ids is not null");
            return (Criteria) this;
        }

        public Criteria andReplyIdsEqualTo(String value) {
            addCriterion("reply_ids =", value, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyIdsNotEqualTo(String value) {
            addCriterion("reply_ids <>", value, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyIdsGreaterThan(String value) {
            addCriterion("reply_ids >", value, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyIdsGreaterThanOrEqualTo(String value) {
            addCriterion("reply_ids >=", value, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyIdsLessThan(String value) {
            addCriterion("reply_ids <", value, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyIdsLessThanOrEqualTo(String value) {
            addCriterion("reply_ids <=", value, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyIdsLike(String value) {
            addCriterion("reply_ids like", value, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyIdsNotLike(String value) {
            addCriterion("reply_ids not like", value, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyIdsIn(List<String> values) {
            addCriterion("reply_ids in", values, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyIdsNotIn(List<String> values) {
            addCriterion("reply_ids not in", values, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyIdsBetween(String value1, String value2) {
            addCriterion("reply_ids between", value1, value2, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyIdsNotBetween(String value1, String value2) {
            addCriterion("reply_ids not between", value1, value2, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyContentIsNull() {
            addCriterion("reply_content is null");
            return (Criteria) this;
        }

        public Criteria andReplyContentIsNotNull() {
            addCriterion("reply_content is not null");
            return (Criteria) this;
        }

        public Criteria andReplyContentEqualTo(String value) {
            addCriterion("reply_content =", value, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyContentNotEqualTo(String value) {
            addCriterion("reply_content <>", value, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyContentGreaterThan(String value) {
            addCriterion("reply_content >", value, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyContentGreaterThanOrEqualTo(String value) {
            addCriterion("reply_content >=", value, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyContentLessThan(String value) {
            addCriterion("reply_content <", value, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyContentLessThanOrEqualTo(String value) {
            addCriterion("reply_content <=", value, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyContentLike(String value) {
            addCriterion("reply_content like", value, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyContentNotLike(String value) {
            addCriterion("reply_content not like", value, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyContentIn(List<String> values) {
            addCriterion("reply_content in", values, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyContentNotIn(List<String> values) {
            addCriterion("reply_content not in", values, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyContentBetween(String value1, String value2) {
            addCriterion("reply_content between", value1, value2, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyContentNotBetween(String value1, String value2) {
            addCriterion("reply_content not between", value1, value2, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyGoalIsNull() {
            addCriterion("reply_goal is null");
            return (Criteria) this;
        }

        public Criteria andReplyGoalIsNotNull() {
            addCriterion("reply_goal is not null");
            return (Criteria) this;
        }

        public Criteria andReplyGoalEqualTo(Integer value) {
            addCriterion("reply_goal =", value, "replyGoal");
            return (Criteria) this;
        }

        public Criteria andReplyGoalNotEqualTo(Integer value) {
            addCriterion("reply_goal <>", value, "replyGoal");
            return (Criteria) this;
        }

        public Criteria andReplyGoalGreaterThan(Integer value) {
            addCriterion("reply_goal >", value, "replyGoal");
            return (Criteria) this;
        }

        public Criteria andReplyGoalGreaterThanOrEqualTo(Integer value) {
            addCriterion("reply_goal >=", value, "replyGoal");
            return (Criteria) this;
        }

        public Criteria andReplyGoalLessThan(Integer value) {
            addCriterion("reply_goal <", value, "replyGoal");
            return (Criteria) this;
        }

        public Criteria andReplyGoalLessThanOrEqualTo(Integer value) {
            addCriterion("reply_goal <=", value, "replyGoal");
            return (Criteria) this;
        }

        public Criteria andReplyGoalIn(List<Integer> values) {
            addCriterion("reply_goal in", values, "replyGoal");
            return (Criteria) this;
        }

        public Criteria andReplyGoalNotIn(List<Integer> values) {
            addCriterion("reply_goal not in", values, "replyGoal");
            return (Criteria) this;
        }

        public Criteria andReplyGoalBetween(Integer value1, Integer value2) {
            addCriterion("reply_goal between", value1, value2, "replyGoal");
            return (Criteria) this;
        }

        public Criteria andReplyGoalNotBetween(Integer value1, Integer value2) {
            addCriterion("reply_goal not between", value1, value2, "replyGoal");
            return (Criteria) this;
        }

        public Criteria andIsrightIsNull() {
            addCriterion("isRight is null");
            return (Criteria) this;
        }

        public Criteria andIsrightIsNotNull() {
            addCriterion("isRight is not null");
            return (Criteria) this;
        }

        public Criteria andIsrightEqualTo(Integer value) {
            addCriterion("isRight =", value, "isright");
            return (Criteria) this;
        }

        public Criteria andIsrightNotEqualTo(Integer value) {
            addCriterion("isRight <>", value, "isright");
            return (Criteria) this;
        }

        public Criteria andIsrightGreaterThan(Integer value) {
            addCriterion("isRight >", value, "isright");
            return (Criteria) this;
        }

        public Criteria andIsrightGreaterThanOrEqualTo(Integer value) {
            addCriterion("isRight >=", value, "isright");
            return (Criteria) this;
        }

        public Criteria andIsrightLessThan(Integer value) {
            addCriterion("isRight <", value, "isright");
            return (Criteria) this;
        }

        public Criteria andIsrightLessThanOrEqualTo(Integer value) {
            addCriterion("isRight <=", value, "isright");
            return (Criteria) this;
        }

        public Criteria andIsrightIn(List<Integer> values) {
            addCriterion("isRight in", values, "isright");
            return (Criteria) this;
        }

        public Criteria andIsrightNotIn(List<Integer> values) {
            addCriterion("isRight not in", values, "isright");
            return (Criteria) this;
        }

        public Criteria andIsrightBetween(Integer value1, Integer value2) {
            addCriterion("isRight between", value1, value2, "isright");
            return (Criteria) this;
        }

        public Criteria andIsrightNotBetween(Integer value1, Integer value2) {
            addCriterion("isRight not between", value1, value2, "isright");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reply
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}