package com.zerozrz.bean;

public class Reply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.reply_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer replyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.answer_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer answerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.question_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.reply_ids
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private String replyIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.reply_content
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private String replyContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.reply_goal
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer replyGoal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.isRight
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer isright;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.reply_id
     *
     * @return the value of reply.reply_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.reply_id
     *
     * @param replyId the value for reply.reply_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setReplyId(Integer replyId) {
        this.replyId = replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.answer_id
     *
     * @return the value of reply.answer_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getAnswerId() {
        return answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.answer_id
     *
     * @param answerId the value for reply.answer_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setAnswerId(Integer answerId) {
        this.answerId = answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.question_id
     *
     * @return the value of reply.question_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.question_id
     *
     * @param questionId the value for reply.question_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.reply_ids
     *
     * @return the value of reply.reply_ids
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public String getReplyIds() {
        return replyIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.reply_ids
     *
     * @param replyIds the value for reply.reply_ids
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setReplyIds(String replyIds) {
        this.replyIds = replyIds == null ? null : replyIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.reply_content
     *
     * @return the value of reply.reply_content
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public String getReplyContent() {
        return replyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.reply_content
     *
     * @param replyContent the value for reply.reply_content
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent == null ? null : replyContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.reply_goal
     *
     * @return the value of reply.reply_goal
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getReplyGoal() {
        return replyGoal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.reply_goal
     *
     * @param replyGoal the value for reply.reply_goal
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setReplyGoal(Integer replyGoal) {
        this.replyGoal = replyGoal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.isRight
     *
     * @return the value of reply.isRight
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getIsright() {
        return isright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.isRight
     *
     * @param isright the value for reply.isRight
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setIsright(Integer isright) {
        this.isright = isright;
    }

	@Override
	public String toString() {
		return "Reply [replyId=" + replyId + ", answerId=" + answerId + ", questionId=" + questionId + ", replyIds="
				+ replyIds + ", replyContent=" + replyContent + ", replyGoal=" + replyGoal + ", isright=" + isright
				+ "]";
	}
    
}