package com.zerozrz.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SurveyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public SurveyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSurveyIdIsNull() {
            addCriterion("survey_id is null");
            return (Criteria) this;
        }

        public Criteria andSurveyIdIsNotNull() {
            addCriterion("survey_id is not null");
            return (Criteria) this;
        }

        public Criteria andSurveyIdEqualTo(Integer value) {
            addCriterion("survey_id =", value, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdNotEqualTo(Integer value) {
            addCriterion("survey_id <>", value, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdGreaterThan(Integer value) {
            addCriterion("survey_id >", value, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("survey_id >=", value, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdLessThan(Integer value) {
            addCriterion("survey_id <", value, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdLessThanOrEqualTo(Integer value) {
            addCriterion("survey_id <=", value, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdIn(List<Integer> values) {
            addCriterion("survey_id in", values, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdNotIn(List<Integer> values) {
            addCriterion("survey_id not in", values, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdBetween(Integer value1, Integer value2) {
            addCriterion("survey_id between", value1, value2, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("survey_id not between", value1, value2, "surveyId");
            return (Criteria) this;
        }

        public Criteria andSurveyTypeIsNull() {
            addCriterion("survey_type is null");
            return (Criteria) this;
        }

        public Criteria andSurveyTypeIsNotNull() {
            addCriterion("survey_type is not null");
            return (Criteria) this;
        }

        public Criteria andSurveyTypeEqualTo(Integer value) {
            addCriterion("survey_type =", value, "surveyType");
            return (Criteria) this;
        }

        public Criteria andSurveyTypeNotEqualTo(Integer value) {
            addCriterion("survey_type <>", value, "surveyType");
            return (Criteria) this;
        }

        public Criteria andSurveyTypeGreaterThan(Integer value) {
            addCriterion("survey_type >", value, "surveyType");
            return (Criteria) this;
        }

        public Criteria andSurveyTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("survey_type >=", value, "surveyType");
            return (Criteria) this;
        }

        public Criteria andSurveyTypeLessThan(Integer value) {
            addCriterion("survey_type <", value, "surveyType");
            return (Criteria) this;
        }

        public Criteria andSurveyTypeLessThanOrEqualTo(Integer value) {
            addCriterion("survey_type <=", value, "surveyType");
            return (Criteria) this;
        }

        public Criteria andSurveyTypeIn(List<Integer> values) {
            addCriterion("survey_type in", values, "surveyType");
            return (Criteria) this;
        }

        public Criteria andSurveyTypeNotIn(List<Integer> values) {
            addCriterion("survey_type not in", values, "surveyType");
            return (Criteria) this;
        }

        public Criteria andSurveyTypeBetween(Integer value1, Integer value2) {
            addCriterion("survey_type between", value1, value2, "surveyType");
            return (Criteria) this;
        }

        public Criteria andSurveyTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("survey_type not between", value1, value2, "surveyType");
            return (Criteria) this;
        }

        public Criteria andSurveyNameIsNull() {
            addCriterion("survey_name is null");
            return (Criteria) this;
        }

        public Criteria andSurveyNameIsNotNull() {
            addCriterion("survey_name is not null");
            return (Criteria) this;
        }

        public Criteria andSurveyNameEqualTo(String value) {
            addCriterion("survey_name =", value, "surveyName");
            return (Criteria) this;
        }

        public Criteria andSurveyNameNotEqualTo(String value) {
            addCriterion("survey_name <>", value, "surveyName");
            return (Criteria) this;
        }

        public Criteria andSurveyNameGreaterThan(String value) {
            addCriterion("survey_name >", value, "surveyName");
            return (Criteria) this;
        }

        public Criteria andSurveyNameGreaterThanOrEqualTo(String value) {
            addCriterion("survey_name >=", value, "surveyName");
            return (Criteria) this;
        }

        public Criteria andSurveyNameLessThan(String value) {
            addCriterion("survey_name <", value, "surveyName");
            return (Criteria) this;
        }

        public Criteria andSurveyNameLessThanOrEqualTo(String value) {
            addCriterion("survey_name <=", value, "surveyName");
            return (Criteria) this;
        }

        public Criteria andSurveyNameLike(String value) {
            addCriterion("survey_name like", value, "surveyName");
            return (Criteria) this;
        }

        public Criteria andSurveyNameNotLike(String value) {
            addCriterion("survey_name not like", value, "surveyName");
            return (Criteria) this;
        }

        public Criteria andSurveyNameIn(List<String> values) {
            addCriterion("survey_name in", values, "surveyName");
            return (Criteria) this;
        }

        public Criteria andSurveyNameNotIn(List<String> values) {
            addCriterion("survey_name not in", values, "surveyName");
            return (Criteria) this;
        }

        public Criteria andSurveyNameBetween(String value1, String value2) {
            addCriterion("survey_name between", value1, value2, "surveyName");
            return (Criteria) this;
        }

        public Criteria andSurveyNameNotBetween(String value1, String value2) {
            addCriterion("survey_name not between", value1, value2, "surveyName");
            return (Criteria) this;
        }

        public Criteria andSurveyExplainIsNull() {
            addCriterion("survey_explain is null");
            return (Criteria) this;
        }

        public Criteria andSurveyExplainIsNotNull() {
            addCriterion("survey_explain is not null");
            return (Criteria) this;
        }

        public Criteria andSurveyExplainEqualTo(String value) {
            addCriterion("survey_explain =", value, "surveyExplain");
            return (Criteria) this;
        }

        public Criteria andSurveyExplainNotEqualTo(String value) {
            addCriterion("survey_explain <>", value, "surveyExplain");
            return (Criteria) this;
        }

        public Criteria andSurveyExplainGreaterThan(String value) {
            addCriterion("survey_explain >", value, "surveyExplain");
            return (Criteria) this;
        }

        public Criteria andSurveyExplainGreaterThanOrEqualTo(String value) {
            addCriterion("survey_explain >=", value, "surveyExplain");
            return (Criteria) this;
        }

        public Criteria andSurveyExplainLessThan(String value) {
            addCriterion("survey_explain <", value, "surveyExplain");
            return (Criteria) this;
        }

        public Criteria andSurveyExplainLessThanOrEqualTo(String value) {
            addCriterion("survey_explain <=", value, "surveyExplain");
            return (Criteria) this;
        }

        public Criteria andSurveyExplainLike(String value) {
            addCriterion("survey_explain like", value, "surveyExplain");
            return (Criteria) this;
        }

        public Criteria andSurveyExplainNotLike(String value) {
            addCriterion("survey_explain not like", value, "surveyExplain");
            return (Criteria) this;
        }

        public Criteria andSurveyExplainIn(List<String> values) {
            addCriterion("survey_explain in", values, "surveyExplain");
            return (Criteria) this;
        }

        public Criteria andSurveyExplainNotIn(List<String> values) {
            addCriterion("survey_explain not in", values, "surveyExplain");
            return (Criteria) this;
        }

        public Criteria andSurveyExplainBetween(String value1, String value2) {
            addCriterion("survey_explain between", value1, value2, "surveyExplain");
            return (Criteria) this;
        }

        public Criteria andSurveyExplainNotBetween(String value1, String value2) {
            addCriterion("survey_explain not between", value1, value2, "surveyExplain");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andTimeCreateIsNull() {
            addCriterion("time_create is null");
            return (Criteria) this;
        }

        public Criteria andTimeCreateIsNotNull() {
            addCriterion("time_create is not null");
            return (Criteria) this;
        }

        public Criteria andTimeCreateEqualTo(Date value) {
            addCriterion("time_create =", value, "timeCreate");
            return (Criteria) this;
        }

        public Criteria andTimeCreateNotEqualTo(Date value) {
            addCriterion("time_create <>", value, "timeCreate");
            return (Criteria) this;
        }

        public Criteria andTimeCreateGreaterThan(Date value) {
            addCriterion("time_create >", value, "timeCreate");
            return (Criteria) this;
        }

        public Criteria andTimeCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("time_create >=", value, "timeCreate");
            return (Criteria) this;
        }

        public Criteria andTimeCreateLessThan(Date value) {
            addCriterion("time_create <", value, "timeCreate");
            return (Criteria) this;
        }

        public Criteria andTimeCreateLessThanOrEqualTo(Date value) {
            addCriterion("time_create <=", value, "timeCreate");
            return (Criteria) this;
        }

        public Criteria andTimeCreateIn(List<Date> values) {
            addCriterion("time_create in", values, "timeCreate");
            return (Criteria) this;
        }

        public Criteria andTimeCreateNotIn(List<Date> values) {
            addCriterion("time_create not in", values, "timeCreate");
            return (Criteria) this;
        }

        public Criteria andTimeCreateBetween(Date value1, Date value2) {
            addCriterion("time_create between", value1, value2, "timeCreate");
            return (Criteria) this;
        }

        public Criteria andTimeCreateNotBetween(Date value1, Date value2) {
            addCriterion("time_create not between", value1, value2, "timeCreate");
            return (Criteria) this;
        }

        public Criteria andTimeStartIsNull() {
            addCriterion("time_start is null");
            return (Criteria) this;
        }

        public Criteria andTimeStartIsNotNull() {
            addCriterion("time_start is not null");
            return (Criteria) this;
        }

        public Criteria andTimeStartEqualTo(Date value) {
            addCriterion("time_start =", value, "timeStart");
            return (Criteria) this;
        }

        public Criteria andTimeStartNotEqualTo(Date value) {
            addCriterion("time_start <>", value, "timeStart");
            return (Criteria) this;
        }

        public Criteria andTimeStartGreaterThan(Date value) {
            addCriterion("time_start >", value, "timeStart");
            return (Criteria) this;
        }

        public Criteria andTimeStartGreaterThanOrEqualTo(Date value) {
            addCriterion("time_start >=", value, "timeStart");
            return (Criteria) this;
        }

        public Criteria andTimeStartLessThan(Date value) {
            addCriterion("time_start <", value, "timeStart");
            return (Criteria) this;
        }

        public Criteria andTimeStartLessThanOrEqualTo(Date value) {
            addCriterion("time_start <=", value, "timeStart");
            return (Criteria) this;
        }

        public Criteria andTimeStartIn(List<Date> values) {
            addCriterion("time_start in", values, "timeStart");
            return (Criteria) this;
        }

        public Criteria andTimeStartNotIn(List<Date> values) {
            addCriterion("time_start not in", values, "timeStart");
            return (Criteria) this;
        }

        public Criteria andTimeStartBetween(Date value1, Date value2) {
            addCriterion("time_start between", value1, value2, "timeStart");
            return (Criteria) this;
        }

        public Criteria andTimeStartNotBetween(Date value1, Date value2) {
            addCriterion("time_start not between", value1, value2, "timeStart");
            return (Criteria) this;
        }

        public Criteria andTimeEndIsNull() {
            addCriterion("time_end is null");
            return (Criteria) this;
        }

        public Criteria andTimeEndIsNotNull() {
            addCriterion("time_end is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEndEqualTo(Date value) {
            addCriterion("time_end =", value, "timeEnd");
            return (Criteria) this;
        }

        public Criteria andTimeEndNotEqualTo(Date value) {
            addCriterion("time_end <>", value, "timeEnd");
            return (Criteria) this;
        }

        public Criteria andTimeEndGreaterThan(Date value) {
            addCriterion("time_end >", value, "timeEnd");
            return (Criteria) this;
        }

        public Criteria andTimeEndGreaterThanOrEqualTo(Date value) {
            addCriterion("time_end >=", value, "timeEnd");
            return (Criteria) this;
        }

        public Criteria andTimeEndLessThan(Date value) {
            addCriterion("time_end <", value, "timeEnd");
            return (Criteria) this;
        }

        public Criteria andTimeEndLessThanOrEqualTo(Date value) {
            addCriterion("time_end <=", value, "timeEnd");
            return (Criteria) this;
        }

        public Criteria andTimeEndIn(List<Date> values) {
            addCriterion("time_end in", values, "timeEnd");
            return (Criteria) this;
        }

        public Criteria andTimeEndNotIn(List<Date> values) {
            addCriterion("time_end not in", values, "timeEnd");
            return (Criteria) this;
        }

        public Criteria andTimeEndBetween(Date value1, Date value2) {
            addCriterion("time_end between", value1, value2, "timeEnd");
            return (Criteria) this;
        }

        public Criteria andTimeEndNotBetween(Date value1, Date value2) {
            addCriterion("time_end not between", value1, value2, "timeEnd");
            return (Criteria) this;
        }

        public Criteria andSurveyStatusIsNull() {
            addCriterion("survey_status is null");
            return (Criteria) this;
        }

        public Criteria andSurveyStatusIsNotNull() {
            addCriterion("survey_status is not null");
            return (Criteria) this;
        }

        public Criteria andSurveyStatusEqualTo(Integer value) {
            addCriterion("survey_status =", value, "surveyStatus");
            return (Criteria) this;
        }

        public Criteria andSurveyStatusNotEqualTo(Integer value) {
            addCriterion("survey_status <>", value, "surveyStatus");
            return (Criteria) this;
        }

        public Criteria andSurveyStatusGreaterThan(Integer value) {
            addCriterion("survey_status >", value, "surveyStatus");
            return (Criteria) this;
        }

        public Criteria andSurveyStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("survey_status >=", value, "surveyStatus");
            return (Criteria) this;
        }

        public Criteria andSurveyStatusLessThan(Integer value) {
            addCriterion("survey_status <", value, "surveyStatus");
            return (Criteria) this;
        }

        public Criteria andSurveyStatusLessThanOrEqualTo(Integer value) {
            addCriterion("survey_status <=", value, "surveyStatus");
            return (Criteria) this;
        }

        public Criteria andSurveyStatusIn(List<Integer> values) {
            addCriterion("survey_status in", values, "surveyStatus");
            return (Criteria) this;
        }

        public Criteria andSurveyStatusNotIn(List<Integer> values) {
            addCriterion("survey_status not in", values, "surveyStatus");
            return (Criteria) this;
        }

        public Criteria andSurveyStatusBetween(Integer value1, Integer value2) {
            addCriterion("survey_status between", value1, value2, "surveyStatus");
            return (Criteria) this;
        }

        public Criteria andSurveyStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("survey_status not between", value1, value2, "surveyStatus");
            return (Criteria) this;
        }

        public Criteria andIsrandomIsNull() {
            addCriterion("isRandom is null");
            return (Criteria) this;
        }

        public Criteria andIsrandomIsNotNull() {
            addCriterion("isRandom is not null");
            return (Criteria) this;
        }

        public Criteria andIsrandomEqualTo(Integer value) {
            addCriterion("isRandom =", value, "israndom");
            return (Criteria) this;
        }

        public Criteria andIsrandomNotEqualTo(Integer value) {
            addCriterion("isRandom <>", value, "israndom");
            return (Criteria) this;
        }

        public Criteria andIsrandomGreaterThan(Integer value) {
            addCriterion("isRandom >", value, "israndom");
            return (Criteria) this;
        }

        public Criteria andIsrandomGreaterThanOrEqualTo(Integer value) {
            addCriterion("isRandom >=", value, "israndom");
            return (Criteria) this;
        }

        public Criteria andIsrandomLessThan(Integer value) {
            addCriterion("isRandom <", value, "israndom");
            return (Criteria) this;
        }

        public Criteria andIsrandomLessThanOrEqualTo(Integer value) {
            addCriterion("isRandom <=", value, "israndom");
            return (Criteria) this;
        }

        public Criteria andIsrandomIn(List<Integer> values) {
            addCriterion("isRandom in", values, "israndom");
            return (Criteria) this;
        }

        public Criteria andIsrandomNotIn(List<Integer> values) {
            addCriterion("isRandom not in", values, "israndom");
            return (Criteria) this;
        }

        public Criteria andIsrandomBetween(Integer value1, Integer value2) {
            addCriterion("isRandom between", value1, value2, "israndom");
            return (Criteria) this;
        }

        public Criteria andIsrandomNotBetween(Integer value1, Integer value2) {
            addCriterion("isRandom not between", value1, value2, "israndom");
            return (Criteria) this;
        }

        public Criteria andQuestionNumsIsNull() {
            addCriterion("question_nums is null");
            return (Criteria) this;
        }

        public Criteria andQuestionNumsIsNotNull() {
            addCriterion("question_nums is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionNumsEqualTo(Integer value) {
            addCriterion("question_nums =", value, "questionNums");
            return (Criteria) this;
        }

        public Criteria andQuestionNumsNotEqualTo(Integer value) {
            addCriterion("question_nums <>", value, "questionNums");
            return (Criteria) this;
        }

        public Criteria andQuestionNumsGreaterThan(Integer value) {
            addCriterion("question_nums >", value, "questionNums");
            return (Criteria) this;
        }

        public Criteria andQuestionNumsGreaterThanOrEqualTo(Integer value) {
            addCriterion("question_nums >=", value, "questionNums");
            return (Criteria) this;
        }

        public Criteria andQuestionNumsLessThan(Integer value) {
            addCriterion("question_nums <", value, "questionNums");
            return (Criteria) this;
        }

        public Criteria andQuestionNumsLessThanOrEqualTo(Integer value) {
            addCriterion("question_nums <=", value, "questionNums");
            return (Criteria) this;
        }

        public Criteria andQuestionNumsIn(List<Integer> values) {
            addCriterion("question_nums in", values, "questionNums");
            return (Criteria) this;
        }

        public Criteria andQuestionNumsNotIn(List<Integer> values) {
            addCriterion("question_nums not in", values, "questionNums");
            return (Criteria) this;
        }

        public Criteria andQuestionNumsBetween(Integer value1, Integer value2) {
            addCriterion("question_nums between", value1, value2, "questionNums");
            return (Criteria) this;
        }

        public Criteria andQuestionNumsNotBetween(Integer value1, Integer value2) {
            addCriterion("question_nums not between", value1, value2, "questionNums");
            return (Criteria) this;
        }

        public Criteria andTestScoreIsNull() {
            addCriterion("test_score is null");
            return (Criteria) this;
        }

        public Criteria andTestScoreIsNotNull() {
            addCriterion("test_score is not null");
            return (Criteria) this;
        }

        public Criteria andTestScoreEqualTo(Integer value) {
            addCriterion("test_score =", value, "testScore");
            return (Criteria) this;
        }

        public Criteria andTestScoreNotEqualTo(Integer value) {
            addCriterion("test_score <>", value, "testScore");
            return (Criteria) this;
        }

        public Criteria andTestScoreGreaterThan(Integer value) {
            addCriterion("test_score >", value, "testScore");
            return (Criteria) this;
        }

        public Criteria andTestScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("test_score >=", value, "testScore");
            return (Criteria) this;
        }

        public Criteria andTestScoreLessThan(Integer value) {
            addCriterion("test_score <", value, "testScore");
            return (Criteria) this;
        }

        public Criteria andTestScoreLessThanOrEqualTo(Integer value) {
            addCriterion("test_score <=", value, "testScore");
            return (Criteria) this;
        }

        public Criteria andTestScoreIn(List<Integer> values) {
            addCriterion("test_score in", values, "testScore");
            return (Criteria) this;
        }

        public Criteria andTestScoreNotIn(List<Integer> values) {
            addCriterion("test_score not in", values, "testScore");
            return (Criteria) this;
        }

        public Criteria andTestScoreBetween(Integer value1, Integer value2) {
            addCriterion("test_score between", value1, value2, "testScore");
            return (Criteria) this;
        }

        public Criteria andTestScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("test_score not between", value1, value2, "testScore");
            return (Criteria) this;
        }

        public Criteria andTestTimeIsNull() {
            addCriterion("test_time is null");
            return (Criteria) this;
        }

        public Criteria andTestTimeIsNotNull() {
            addCriterion("test_time is not null");
            return (Criteria) this;
        }

        public Criteria andTestTimeEqualTo(Date value) {
            addCriterion("test_time =", value, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeNotEqualTo(Date value) {
            addCriterion("test_time <>", value, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeGreaterThan(Date value) {
            addCriterion("test_time >", value, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("test_time >=", value, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeLessThan(Date value) {
            addCriterion("test_time <", value, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeLessThanOrEqualTo(Date value) {
            addCriterion("test_time <=", value, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeIn(List<Date> values) {
            addCriterion("test_time in", values, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeNotIn(List<Date> values) {
            addCriterion("test_time not in", values, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeBetween(Date value1, Date value2) {
            addCriterion("test_time between", value1, value2, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeNotBetween(Date value1, Date value2) {
            addCriterion("test_time not between", value1, value2, "testTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table survey
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}