package com.zerozrz.bean;

public class SurveyOption {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_option.option_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer optionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_option.question_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_option.option_label
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private String optionLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_option.option_content
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private String optionContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_option.option_sort
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer optionSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_option.isCorrect
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer iscorrect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_option.option_score
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer optionScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_option.option_votes
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer optionVotes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_option.option_id
     *
     * @return the value of survey_option.option_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getOptionId() {
        return optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_option.option_id
     *
     * @param optionId the value for survey_option.option_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setOptionId(Integer optionId) {
        this.optionId = optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_option.question_id
     *
     * @return the value of survey_option.question_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_option.question_id
     *
     * @param questionId the value for survey_option.question_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_option.option_label
     *
     * @return the value of survey_option.option_label
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public String getOptionLabel() {
        return optionLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_option.option_label
     *
     * @param optionLabel the value for survey_option.option_label
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setOptionLabel(String optionLabel) {
        this.optionLabel = optionLabel == null ? null : optionLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_option.option_content
     *
     * @return the value of survey_option.option_content
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public String getOptionContent() {
        return optionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_option.option_content
     *
     * @param optionContent the value for survey_option.option_content
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setOptionContent(String optionContent) {
        this.optionContent = optionContent == null ? null : optionContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_option.option_sort
     *
     * @return the value of survey_option.option_sort
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getOptionSort() {
        return optionSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_option.option_sort
     *
     * @param optionSort the value for survey_option.option_sort
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setOptionSort(Integer optionSort) {
        this.optionSort = optionSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_option.isCorrect
     *
     * @return the value of survey_option.isCorrect
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getIscorrect() {
        return iscorrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_option.isCorrect
     *
     * @param iscorrect the value for survey_option.isCorrect
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setIscorrect(Integer iscorrect) {
        this.iscorrect = iscorrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_option.option_score
     *
     * @return the value of survey_option.option_score
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getOptionScore() {
        return optionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_option.option_score
     *
     * @param optionScore the value for survey_option.option_score
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setOptionScore(Integer optionScore) {
        this.optionScore = optionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_option.option_votes
     *
     * @return the value of survey_option.option_votes
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getOptionVotes() {
        return optionVotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_option.option_votes
     *
     * @param optionVotes the value for survey_option.option_votes
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setOptionVotes(Integer optionVotes) {
        this.optionVotes = optionVotes;
    }

	@Override
	public String toString() {
		return "SurveyOption [optionId=" + optionId + ", questionId=" + questionId + ", optionLabel=" + optionLabel
				+ ", optionContent=" + optionContent + ", optionSort=" + optionSort + ", iscorrect=" + iscorrect
				+ ", optionScore=" + optionScore + ", optionVotes=" + optionVotes + "]";
	}
    
    
    
}