package com.zerozrz.bean;

public class SurveyQuestion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_question.question_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_question.survey_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer surveyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_question.question_type
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer questionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_question.question_title
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private String questionTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_question.question_explain
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private String questionExplain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_question.isRequired
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private String isrequired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_question.question_sort
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private String questionSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_question.question_score
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer questionScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_question.isRandom
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer israndom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_question.question_id
     *
     * @return the value of survey_question.question_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_question.question_id
     *
     * @param questionId the value for survey_question.question_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_question.survey_id
     *
     * @return the value of survey_question.survey_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getSurveyId() {
        return surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_question.survey_id
     *
     * @param surveyId the value for survey_question.survey_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setSurveyId(Integer surveyId) {
        this.surveyId = surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_question.question_type
     *
     * @return the value of survey_question.question_type
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getQuestionType() {
        return questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_question.question_type
     *
     * @param questionType the value for survey_question.question_type
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setQuestionType(Integer questionType) {
        this.questionType = questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_question.question_title
     *
     * @return the value of survey_question.question_title
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public String getQuestionTitle() {
        return questionTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_question.question_title
     *
     * @param questionTitle the value for survey_question.question_title
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setQuestionTitle(String questionTitle) {
        this.questionTitle = questionTitle == null ? null : questionTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_question.question_explain
     *
     * @return the value of survey_question.question_explain
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public String getQuestionExplain() {
        return questionExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_question.question_explain
     *
     * @param questionExplain the value for survey_question.question_explain
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setQuestionExplain(String questionExplain) {
        this.questionExplain = questionExplain == null ? null : questionExplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_question.isRequired
     *
     * @return the value of survey_question.isRequired
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public String getIsrequired() {
        return isrequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_question.isRequired
     *
     * @param isrequired the value for survey_question.isRequired
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setIsrequired(String isrequired) {
        this.isrequired = isrequired == null ? null : isrequired.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_question.question_sort
     *
     * @return the value of survey_question.question_sort
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public String getQuestionSort() {
        return questionSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_question.question_sort
     *
     * @param questionSort the value for survey_question.question_sort
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setQuestionSort(String questionSort) {
        this.questionSort = questionSort == null ? null : questionSort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_question.question_score
     *
     * @return the value of survey_question.question_score
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getQuestionScore() {
        return questionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_question.question_score
     *
     * @param questionScore the value for survey_question.question_score
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setQuestionScore(Integer questionScore) {
        this.questionScore = questionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_question.isRandom
     *
     * @return the value of survey_question.isRandom
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getIsrandom() {
        return israndom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_question.isRandom
     *
     * @param israndom the value for survey_question.isRandom
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setIsrandom(Integer israndom) {
        this.israndom = israndom;
    }

	@Override
	public String toString() {
		return "SurveyQuestion [questionId=" + questionId + ", surveyId=" + surveyId + ", questionType=" + questionType
				+ ", questionTitle=" + questionTitle + ", questionExplain=" + questionExplain + ", isrequired="
				+ isrequired + ", questionSort=" + questionSort + ", questionScore=" + questionScore + ", israndom="
				+ israndom + "]";
	}
    
    
    
}