package com.zerozrz.bean;

import java.util.ArrayList;
import java.util.List;

public class SurveyOptionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public SurveyOptionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOptionIdIsNull() {
            addCriterion("option_id is null");
            return (Criteria) this;
        }

        public Criteria andOptionIdIsNotNull() {
            addCriterion("option_id is not null");
            return (Criteria) this;
        }

        public Criteria andOptionIdEqualTo(Integer value) {
            addCriterion("option_id =", value, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdNotEqualTo(Integer value) {
            addCriterion("option_id <>", value, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdGreaterThan(Integer value) {
            addCriterion("option_id >", value, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("option_id >=", value, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdLessThan(Integer value) {
            addCriterion("option_id <", value, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdLessThanOrEqualTo(Integer value) {
            addCriterion("option_id <=", value, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdIn(List<Integer> values) {
            addCriterion("option_id in", values, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdNotIn(List<Integer> values) {
            addCriterion("option_id not in", values, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdBetween(Integer value1, Integer value2) {
            addCriterion("option_id between", value1, value2, "optionId");
            return (Criteria) this;
        }

        public Criteria andOptionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("option_id not between", value1, value2, "optionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIsNull() {
            addCriterion("question_id is null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIsNotNull() {
            addCriterion("question_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdEqualTo(Integer value) {
            addCriterion("question_id =", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotEqualTo(Integer value) {
            addCriterion("question_id <>", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThan(Integer value) {
            addCriterion("question_id >", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("question_id >=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThan(Integer value) {
            addCriterion("question_id <", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThanOrEqualTo(Integer value) {
            addCriterion("question_id <=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIn(List<Integer> values) {
            addCriterion("question_id in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotIn(List<Integer> values) {
            addCriterion("question_id not in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdBetween(Integer value1, Integer value2) {
            addCriterion("question_id between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("question_id not between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andOptionLabelIsNull() {
            addCriterion("option_label is null");
            return (Criteria) this;
        }

        public Criteria andOptionLabelIsNotNull() {
            addCriterion("option_label is not null");
            return (Criteria) this;
        }

        public Criteria andOptionLabelEqualTo(String value) {
            addCriterion("option_label =", value, "optionLabel");
            return (Criteria) this;
        }

        public Criteria andOptionLabelNotEqualTo(String value) {
            addCriterion("option_label <>", value, "optionLabel");
            return (Criteria) this;
        }

        public Criteria andOptionLabelGreaterThan(String value) {
            addCriterion("option_label >", value, "optionLabel");
            return (Criteria) this;
        }

        public Criteria andOptionLabelGreaterThanOrEqualTo(String value) {
            addCriterion("option_label >=", value, "optionLabel");
            return (Criteria) this;
        }

        public Criteria andOptionLabelLessThan(String value) {
            addCriterion("option_label <", value, "optionLabel");
            return (Criteria) this;
        }

        public Criteria andOptionLabelLessThanOrEqualTo(String value) {
            addCriterion("option_label <=", value, "optionLabel");
            return (Criteria) this;
        }

        public Criteria andOptionLabelLike(String value) {
            addCriterion("option_label like", value, "optionLabel");
            return (Criteria) this;
        }

        public Criteria andOptionLabelNotLike(String value) {
            addCriterion("option_label not like", value, "optionLabel");
            return (Criteria) this;
        }

        public Criteria andOptionLabelIn(List<String> values) {
            addCriterion("option_label in", values, "optionLabel");
            return (Criteria) this;
        }

        public Criteria andOptionLabelNotIn(List<String> values) {
            addCriterion("option_label not in", values, "optionLabel");
            return (Criteria) this;
        }

        public Criteria andOptionLabelBetween(String value1, String value2) {
            addCriterion("option_label between", value1, value2, "optionLabel");
            return (Criteria) this;
        }

        public Criteria andOptionLabelNotBetween(String value1, String value2) {
            addCriterion("option_label not between", value1, value2, "optionLabel");
            return (Criteria) this;
        }

        public Criteria andOptionContentIsNull() {
            addCriterion("option_content is null");
            return (Criteria) this;
        }

        public Criteria andOptionContentIsNotNull() {
            addCriterion("option_content is not null");
            return (Criteria) this;
        }

        public Criteria andOptionContentEqualTo(String value) {
            addCriterion("option_content =", value, "optionContent");
            return (Criteria) this;
        }

        public Criteria andOptionContentNotEqualTo(String value) {
            addCriterion("option_content <>", value, "optionContent");
            return (Criteria) this;
        }

        public Criteria andOptionContentGreaterThan(String value) {
            addCriterion("option_content >", value, "optionContent");
            return (Criteria) this;
        }

        public Criteria andOptionContentGreaterThanOrEqualTo(String value) {
            addCriterion("option_content >=", value, "optionContent");
            return (Criteria) this;
        }

        public Criteria andOptionContentLessThan(String value) {
            addCriterion("option_content <", value, "optionContent");
            return (Criteria) this;
        }

        public Criteria andOptionContentLessThanOrEqualTo(String value) {
            addCriterion("option_content <=", value, "optionContent");
            return (Criteria) this;
        }

        public Criteria andOptionContentLike(String value) {
            addCriterion("option_content like", value, "optionContent");
            return (Criteria) this;
        }

        public Criteria andOptionContentNotLike(String value) {
            addCriterion("option_content not like", value, "optionContent");
            return (Criteria) this;
        }

        public Criteria andOptionContentIn(List<String> values) {
            addCriterion("option_content in", values, "optionContent");
            return (Criteria) this;
        }

        public Criteria andOptionContentNotIn(List<String> values) {
            addCriterion("option_content not in", values, "optionContent");
            return (Criteria) this;
        }

        public Criteria andOptionContentBetween(String value1, String value2) {
            addCriterion("option_content between", value1, value2, "optionContent");
            return (Criteria) this;
        }

        public Criteria andOptionContentNotBetween(String value1, String value2) {
            addCriterion("option_content not between", value1, value2, "optionContent");
            return (Criteria) this;
        }

        public Criteria andOptionSortIsNull() {
            addCriterion("option_sort is null");
            return (Criteria) this;
        }

        public Criteria andOptionSortIsNotNull() {
            addCriterion("option_sort is not null");
            return (Criteria) this;
        }

        public Criteria andOptionSortEqualTo(Integer value) {
            addCriterion("option_sort =", value, "optionSort");
            return (Criteria) this;
        }

        public Criteria andOptionSortNotEqualTo(Integer value) {
            addCriterion("option_sort <>", value, "optionSort");
            return (Criteria) this;
        }

        public Criteria andOptionSortGreaterThan(Integer value) {
            addCriterion("option_sort >", value, "optionSort");
            return (Criteria) this;
        }

        public Criteria andOptionSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("option_sort >=", value, "optionSort");
            return (Criteria) this;
        }

        public Criteria andOptionSortLessThan(Integer value) {
            addCriterion("option_sort <", value, "optionSort");
            return (Criteria) this;
        }

        public Criteria andOptionSortLessThanOrEqualTo(Integer value) {
            addCriterion("option_sort <=", value, "optionSort");
            return (Criteria) this;
        }

        public Criteria andOptionSortIn(List<Integer> values) {
            addCriterion("option_sort in", values, "optionSort");
            return (Criteria) this;
        }

        public Criteria andOptionSortNotIn(List<Integer> values) {
            addCriterion("option_sort not in", values, "optionSort");
            return (Criteria) this;
        }

        public Criteria andOptionSortBetween(Integer value1, Integer value2) {
            addCriterion("option_sort between", value1, value2, "optionSort");
            return (Criteria) this;
        }

        public Criteria andOptionSortNotBetween(Integer value1, Integer value2) {
            addCriterion("option_sort not between", value1, value2, "optionSort");
            return (Criteria) this;
        }

        public Criteria andIscorrectIsNull() {
            addCriterion("isCorrect is null");
            return (Criteria) this;
        }

        public Criteria andIscorrectIsNotNull() {
            addCriterion("isCorrect is not null");
            return (Criteria) this;
        }

        public Criteria andIscorrectEqualTo(Integer value) {
            addCriterion("isCorrect =", value, "iscorrect");
            return (Criteria) this;
        }

        public Criteria andIscorrectNotEqualTo(Integer value) {
            addCriterion("isCorrect <>", value, "iscorrect");
            return (Criteria) this;
        }

        public Criteria andIscorrectGreaterThan(Integer value) {
            addCriterion("isCorrect >", value, "iscorrect");
            return (Criteria) this;
        }

        public Criteria andIscorrectGreaterThanOrEqualTo(Integer value) {
            addCriterion("isCorrect >=", value, "iscorrect");
            return (Criteria) this;
        }

        public Criteria andIscorrectLessThan(Integer value) {
            addCriterion("isCorrect <", value, "iscorrect");
            return (Criteria) this;
        }

        public Criteria andIscorrectLessThanOrEqualTo(Integer value) {
            addCriterion("isCorrect <=", value, "iscorrect");
            return (Criteria) this;
        }

        public Criteria andIscorrectIn(List<Integer> values) {
            addCriterion("isCorrect in", values, "iscorrect");
            return (Criteria) this;
        }

        public Criteria andIscorrectNotIn(List<Integer> values) {
            addCriterion("isCorrect not in", values, "iscorrect");
            return (Criteria) this;
        }

        public Criteria andIscorrectBetween(Integer value1, Integer value2) {
            addCriterion("isCorrect between", value1, value2, "iscorrect");
            return (Criteria) this;
        }

        public Criteria andIscorrectNotBetween(Integer value1, Integer value2) {
            addCriterion("isCorrect not between", value1, value2, "iscorrect");
            return (Criteria) this;
        }

        public Criteria andOptionScoreIsNull() {
            addCriterion("option_score is null");
            return (Criteria) this;
        }

        public Criteria andOptionScoreIsNotNull() {
            addCriterion("option_score is not null");
            return (Criteria) this;
        }

        public Criteria andOptionScoreEqualTo(Integer value) {
            addCriterion("option_score =", value, "optionScore");
            return (Criteria) this;
        }

        public Criteria andOptionScoreNotEqualTo(Integer value) {
            addCriterion("option_score <>", value, "optionScore");
            return (Criteria) this;
        }

        public Criteria andOptionScoreGreaterThan(Integer value) {
            addCriterion("option_score >", value, "optionScore");
            return (Criteria) this;
        }

        public Criteria andOptionScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("option_score >=", value, "optionScore");
            return (Criteria) this;
        }

        public Criteria andOptionScoreLessThan(Integer value) {
            addCriterion("option_score <", value, "optionScore");
            return (Criteria) this;
        }

        public Criteria andOptionScoreLessThanOrEqualTo(Integer value) {
            addCriterion("option_score <=", value, "optionScore");
            return (Criteria) this;
        }

        public Criteria andOptionScoreIn(List<Integer> values) {
            addCriterion("option_score in", values, "optionScore");
            return (Criteria) this;
        }

        public Criteria andOptionScoreNotIn(List<Integer> values) {
            addCriterion("option_score not in", values, "optionScore");
            return (Criteria) this;
        }

        public Criteria andOptionScoreBetween(Integer value1, Integer value2) {
            addCriterion("option_score between", value1, value2, "optionScore");
            return (Criteria) this;
        }

        public Criteria andOptionScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("option_score not between", value1, value2, "optionScore");
            return (Criteria) this;
        }

        public Criteria andOptionVotesIsNull() {
            addCriterion("option_votes is null");
            return (Criteria) this;
        }

        public Criteria andOptionVotesIsNotNull() {
            addCriterion("option_votes is not null");
            return (Criteria) this;
        }

        public Criteria andOptionVotesEqualTo(Integer value) {
            addCriterion("option_votes =", value, "optionVotes");
            return (Criteria) this;
        }

        public Criteria andOptionVotesNotEqualTo(Integer value) {
            addCriterion("option_votes <>", value, "optionVotes");
            return (Criteria) this;
        }

        public Criteria andOptionVotesGreaterThan(Integer value) {
            addCriterion("option_votes >", value, "optionVotes");
            return (Criteria) this;
        }

        public Criteria andOptionVotesGreaterThanOrEqualTo(Integer value) {
            addCriterion("option_votes >=", value, "optionVotes");
            return (Criteria) this;
        }

        public Criteria andOptionVotesLessThan(Integer value) {
            addCriterion("option_votes <", value, "optionVotes");
            return (Criteria) this;
        }

        public Criteria andOptionVotesLessThanOrEqualTo(Integer value) {
            addCriterion("option_votes <=", value, "optionVotes");
            return (Criteria) this;
        }

        public Criteria andOptionVotesIn(List<Integer> values) {
            addCriterion("option_votes in", values, "optionVotes");
            return (Criteria) this;
        }

        public Criteria andOptionVotesNotIn(List<Integer> values) {
            addCriterion("option_votes not in", values, "optionVotes");
            return (Criteria) this;
        }

        public Criteria andOptionVotesBetween(Integer value1, Integer value2) {
            addCriterion("option_votes between", value1, value2, "optionVotes");
            return (Criteria) this;
        }

        public Criteria andOptionVotesNotBetween(Integer value1, Integer value2) {
            addCriterion("option_votes not between", value1, value2, "optionVotes");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table survey_option
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}