package com.zerozrz.bean;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class Survey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.survey_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer surveyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.survey_type
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer surveyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.survey_name
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private String surveyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.survey_explain
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private String surveyExplain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.user_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.time_create
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Date timeCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.time_start
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Date timeStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.time_end
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Date timeEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.survey_status
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer surveyStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.isRandom
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer israndom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.question_nums
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer questionNums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.test_score
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer testScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.test_time
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Date testTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.survey_id
     *
     * @return the value of survey.survey_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getSurveyId() {
        return surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.survey_id
     *
     * @param surveyId the value for survey.survey_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setSurveyId(Integer surveyId) {
        this.surveyId = surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.survey_type
     *
     * @return the value of survey.survey_type
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getSurveyType() {
        return surveyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.survey_type
     *
     * @param surveyType the value for survey.survey_type
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setSurveyType(Integer surveyType) {
        this.surveyType = surveyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.survey_name
     *
     * @return the value of survey.survey_name
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public String getSurveyName() {
        return surveyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.survey_name
     *
     * @param surveyName the value for survey.survey_name
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setSurveyName(String surveyName) {
        this.surveyName = surveyName == null ? null : surveyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.survey_explain
     *
     * @return the value of survey.survey_explain
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public String getSurveyExplain() {
        return surveyExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.survey_explain
     *
     * @param surveyExplain the value for survey.survey_explain
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setSurveyExplain(String surveyExplain) {
        this.surveyExplain = surveyExplain == null ? null : surveyExplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.user_id
     *
     * @return the value of survey.user_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.user_id
     *
     * @param userId the value for survey.user_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.time_create
     *
     * @return the value of survey.time_create
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    public Date getTimeCreate() {
        return timeCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.time_create
     *
     * @param timeCreate the value for survey.time_create
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setTimeCreate(Date timeCreate) {
        this.timeCreate = timeCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.time_start
     *
     * @return the value of survey.time_start
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    public Date getTimeStart() {
        return timeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.time_start
     *
     * @param timeStart the value for survey.time_start
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setTimeStart(Date timeStart) {
        this.timeStart = timeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.time_end
     *
     * @return the value of survey.time_end
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    public Date getTimeEnd() {
        return timeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.time_end
     *
     * @param timeEnd the value for survey.time_end
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setTimeEnd(Date timeEnd) {
        this.timeEnd = timeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.survey_status
     *
     * @return the value of survey.survey_status
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getSurveyStatus() {
        return surveyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.survey_status
     *
     * @param surveyStatus the value for survey.survey_status
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setSurveyStatus(Integer surveyStatus) {
        this.surveyStatus = surveyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.isRandom
     *
     * @return the value of survey.isRandom
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getIsrandom() {
        return israndom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.isRandom
     *
     * @param israndom the value for survey.isRandom
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setIsrandom(Integer israndom) {
        this.israndom = israndom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.question_nums
     *
     * @return the value of survey.question_nums
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getQuestionNums() {
        return questionNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.question_nums
     *
     * @param questionNums the value for survey.question_nums
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setQuestionNums(Integer questionNums) {
        this.questionNums = questionNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.test_score
     *
     * @return the value of survey.test_score
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getTestScore() {
        return testScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.test_score
     *
     * @param testScore the value for survey.test_score
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setTestScore(Integer testScore) {
        this.testScore = testScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.test_time
     *
     * @return the value of survey.test_time
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Date getTestTime() {
        return testTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.test_time
     *
     * @param testTime the value for survey.test_time
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setTestTime(Date testTime) {
        this.testTime = testTime;
    }

	@Override
	public String toString() {
		return "Survey [surveyId=" + surveyId + ", surveyType=" + surveyType + ", surveyName=" + surveyName
				+ ", surveyExplain=" + surveyExplain + ", userId=" + userId + ", timeCreate=" + timeCreate
				+ ", timeStart=" + timeStart + ", timeEnd=" + timeEnd + ", surveyStatus=" + surveyStatus + ", israndom="
				+ israndom + ", questionNums=" + questionNums + ", testScore=" + testScore + ", testTime=" + testTime
				+ "]";
	}
    
    
    
}