package com.zerozrz.bean;

import java.util.Date;

public class UserRecharge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_recharge.recharge_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer rechargeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_recharge.user_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_recharge.recharge_money
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Double rechargeMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_recharge.recharge_time
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private Date rechargeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_recharge.recharge_type
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private String rechargeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_recharge.recharge_explain
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    private String rechargeExplain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_recharge.recharge_id
     *
     * @return the value of user_recharge.recharge_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getRechargeId() {
        return rechargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_recharge.recharge_id
     *
     * @param rechargeId the value for user_recharge.recharge_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setRechargeId(Integer rechargeId) {
        this.rechargeId = rechargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_recharge.user_id
     *
     * @return the value of user_recharge.user_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_recharge.user_id
     *
     * @param userId the value for user_recharge.user_id
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_recharge.recharge_money
     *
     * @return the value of user_recharge.recharge_money
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Double getRechargeMoney() {
        return rechargeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_recharge.recharge_money
     *
     * @param rechargeMoney the value for user_recharge.recharge_money
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setRechargeMoney(Double rechargeMoney) {
        this.rechargeMoney = rechargeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_recharge.recharge_time
     *
     * @return the value of user_recharge.recharge_time
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public Date getRechargeTime() {
        return rechargeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_recharge.recharge_time
     *
     * @param rechargeTime the value for user_recharge.recharge_time
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setRechargeTime(Date rechargeTime) {
        this.rechargeTime = rechargeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_recharge.recharge_type
     *
     * @return the value of user_recharge.recharge_type
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public String getRechargeType() {
        return rechargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_recharge.recharge_type
     *
     * @param rechargeType the value for user_recharge.recharge_type
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setRechargeType(String rechargeType) {
        this.rechargeType = rechargeType == null ? null : rechargeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_recharge.recharge_explain
     *
     * @return the value of user_recharge.recharge_explain
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public String getRechargeExplain() {
        return rechargeExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_recharge.recharge_explain
     *
     * @param rechargeExplain the value for user_recharge.recharge_explain
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    public void setRechargeExplain(String rechargeExplain) {
        this.rechargeExplain = rechargeExplain == null ? null : rechargeExplain.trim();
    }

	@Override
	public String toString() {
		return "UserRecharge [rechargeId=" + rechargeId + ", userId=" + userId + ", rechargeMoney=" + rechargeMoney
				+ ", rechargeTime=" + rechargeTime + ", rechargeType=" + rechargeType + ", rechargeExplain="
				+ rechargeExplain + "]";
	}
    
    
    
}