package com.zerozrz.dao;

import com.zerozrz.bean.Reply;
import com.zerozrz.bean.ReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    long countByExample(ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    int deleteByExample(ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    int insert(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    int insertSelective(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    List<Reply> selectByExample(ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") Reply record, @Param("example") ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    int updateByExample(@Param("record") Reply record, @Param("example") ReplyExample example);
}