package com.zerozrz.dao;

import com.zerozrz.bean.SurveyOption;
import com.zerozrz.bean.SurveyOptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SurveyOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    long countByExample(SurveyOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    int deleteByExample(SurveyOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    int insert(SurveyOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    int insertSelective(SurveyOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    List<SurveyOption> selectByExample(SurveyOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") SurveyOption record, @Param("example") SurveyOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_option
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    int updateByExample(@Param("record") SurveyOption record, @Param("example") SurveyOptionExample example);
}