package com.zerozrz.dao;

import com.zerozrz.bean.Survey;
import com.zerozrz.bean.SurveyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SurveyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    long countByExample(SurveyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    int deleteByExample(SurveyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    int insert(Survey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    int insertSelective(Survey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    List<Survey> selectByExample(SurveyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") Survey record, @Param("example") SurveyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    int updateByExample(@Param("record") Survey record, @Param("example") SurveyExample example);
}