package com.zerozrz.dao;

import com.zerozrz.bean.SurveyQuestion;
import com.zerozrz.bean.SurveyQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SurveyQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_question
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    long countByExample(SurveyQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_question
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    int deleteByExample(SurveyQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_question
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    int insert(SurveyQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_question
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    int insertSelective(SurveyQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_question
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    List<SurveyQuestion> selectByExample(SurveyQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_question
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") SurveyQuestion record, @Param("example") SurveyQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_question
     *
     * @mbg.generated Tue Oct 16 13:36:40 GMT+08:00 2018
     */
    int updateByExample(@Param("record") SurveyQuestion record, @Param("example") SurveyQuestionExample example);
}